version: '3.8'

services:
  backend:
    build: ./DataServer/
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/myapp
      SPRING_DATASOURCE_USERNAME: myappuser
      SPRING_DATASOURCE_PASSWORD: mypassword

  db:
    image: "postgres:13"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: myapp
      POSTGRES_USER: myappuser
      POSTGRES_PASSWORD: mypassword
      
  frontend:
    build: ./frontend-app/
    ports:
      - "3000:3000"
    environment:
      - VUE_APP_TARGET_SERVER_URL="http://backend:8080"
    depends_on:
      - backend

  api:
    build: ./collector-api/
    ports:
      - "4200:4200"
    environment:
      - SERVER_URL="http://backend:8080"
    depends_on:
      - backend
  